### PR TITLE
Fixed all current Scala feature warnings

### PR DESCRIPTION
**Pull request by Madoc**
This will fix _all_ of the current Scala feature warnings during the compile process.

Sometimes, this is achieved by using the specific `import` from `scala.language....`.
But I followed the spirit of our recent meeting, and fixed some Scala feature warnings by changing the code itself.

### CODE REVIEW

**Comment by ghost** [comment]
Can you please rebase the commit? I can't merge it automatically.

**Comment by Madoc** [comment]
Please try again; I _hope_ I fixed it. Let's see.

**Comment by ghost** [comment]
Looks good! Please confirm that you  want to check in the changes for the code Style Settings file with this pull request too - just to be sure that you didn't accidentially commit changes for this file.

**Comment by ghost** [comment]
Got feedback that the code style formatter changes are desired, accepting the PR.

**Pull request merged**
